apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-stocksapp-db
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: lnx1
    path: "/srv/stocks_nfs"
  mountOptions:
    - nfsvers=4.2