apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stocks-app-db-pvc
  namespace: stocks-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-stocksapp-db