apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-app-frontend
  namespace: stocks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stocks-app
      microservice: frontend
  template:
    metadata:
      labels:
        app: stocks-app
        microservice: frontend
    spec:
      containers:
      - image: ady28/stocks-frontend:qual
        imagePullPolicy: Always
        name: stocksfrontend
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 65534
          runAsGroup: 65534
        ports:
        - containerPort: 8080
          name: frontend-port
        volumeMounts:
          - mountPath: /tmp
            name: tmpfs-1
      volumes:
      - name: tmpfs-1
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: stocksfrontend
  namespace: stocks-app
spec:
  selector:
    app: stocks-app
    microservice: frontend
  ports:
  - name: frontend-svc-port
    protocol: TCP
    port: 8080
    targetPort: frontend-port
  type: ClusterIP

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: stocks-app-frontend-ingress
  namespace: stocks-app
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`adidum.ddns.net`) && (PathPrefix(`/`))
    services:
    - kind: Service
      name: stocksfrontend
      namespace: stocks-app
      port: 8080
  tls:
    secretName: ssl-cert
