apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stocks-app-db-pvc
  namespace: stocks-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-stocksapp-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-app-db
  namespace: stocks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stocks-app
      microservice: db
  template:
    metadata:
      labels:
        app: stocks-app
        microservice: db
    spec:
      securityContext:
        fsGroup: 999 
        runAsUser: 999
        runAsGroup: 999
      tolerations:
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        tolerationSeconds: 0
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        tolerationSeconds: 0
      containers:
      - image: mongo:6.0.3-focal
        args: ["--dbpath","/data/db"]
        imagePullPolicy: IfNotPresent
        name: stocksdb
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - "-c"
              - |
                mongosh --eval 'db.serverStatus'
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
          - name: db-data
            mountPath: "/data/db"
          - name: db-creds
            mountPath: "/etc/secrets"
        ports:
        - containerPort: 27017
          name: mongo-db-port
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: "/etc/secrets/stocksmongouser"
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: "/etc/secrets/stocksmongopassword"
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: stocks-app-db-pvc
      - name: db-creds
        secret:
          secretName: db-creds
          optional: false

---

apiVersion: v1
kind: Service
metadata:
  name: stocksdb
  namespace: stocks-app
spec:
  selector:
    app: stocks-app
    microservice: db
  ports:
  - name: mongo-svc-port
    protocol: TCP
    port: 27017
    targetPort: mongo-db-port
  type: ClusterIP