apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-app-competitors
  namespace: stocks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stocks-app
      microservice: competitors
  template:
    metadata:
      labels:
        app: stocks-app
        microservice: competitors
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - image: ady28/stocks-competitors:test
        imagePullPolicy: Always
        name: stockscompetitors
        volumeMounts:
          - name: db-creds
            mountPath: "/run/secrets/stocksmongouser"
            subPath: stocksmongouser
          - name: db-creds
            mountPath: "/run/secrets/stocksmongopassword"
            subPath: stocksmongopassword
        ports:
        - containerPort: 8080
          name: api-comp-port
        env:
        - name: PORT
          value: "8080"
        - name: MONGO_NAME
          value: "stocksdb"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DB
          value: "stocks"
        - name: STOCKS_APP_ENV
          value: "test"
      volumes:
      - name: db-creds
        secret:
          secretName: db-creds
          optional: false
          items:
            - key: stocksmongouser
              path: stocksmongouser
            - key: stocksmongopassword
              path: stocksmongopassword

---

apiVersion: v1
kind: Service
metadata:
  name: stockscompetitors
  namespace: stocks-app
spec:
  selector:
    app: stocks-app
    microservice: competitors
  ports:
  - name: competitors-svc-port
    protocol: TCP
    port: 8080
    targetPort: api-comp-port
  type: ClusterIP
