apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stocks-app-db-pvc
  namespace: stocks-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-stocksapp-db

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stocks-app-db
  namespace: stocks-app
spec:
  serviceName: stocksdb
  replicas: 1
  selector:
    matchLabels:
      app: stocks-app
      microservice: db
  template:
    metadata:
      labels:
        app: stocks-app
        microservice: db
    spec:
      securityContext:
        fsGroup: 999 
        runAsUser: 999
        runAsGroup: 999
      containers:
      - image: mongo:4.4.14-focal
        imagePullPolicy: IfNotPresent
        name: stocksdb
        volumeMounts:
          - name: db-data
            mountPath: "/data"
          - name: db-creds
            mountPath: "/etc/secrets"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: "/etc/secrets/stocksmongouser"
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: "/etc/secrets/stocksmongopassword"
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: stocks-app-db-pvc
      - name: db-creds
        secret:
          secretName: db-creds
          optional: false